// GERADO A MAO, mantido ordenado por BYTES UTF-8 (o que strcmp compara).
// Chave = o portugues que esta no codigo. Ver idioma.h.
  { " carregados", " loaded" },
  { " · Nascido em %s", " · Born %s" },
  { "%.1f MB em %d imagens", "%.1f MB in %d images" },
  { "%d %s · OK para explorar", "%d %s · OK to explore" },
  { "%d MINUTOS RESTANTES", "%d MINUTES LEFT" },
  { "%d de %d", "%d of %d" },
  { "%d de %d dias ativos no mês", "%d of %d active days this month" },
  { "%d de %d episódios", "%d of %d episodes" },
  { "%d de %s de %c%c%c%c", "%d %s %c%c%c%c" },
  { "%d de 8", "%d of 8" },
  { "%d dias ativos no ano", "%d active days this year" },
  { "%d dias ativos · %d dias seguidos no mês", "%d active days · %d-day streak this month" },
  { "%d reproduções", "%d plays" },
  { "%d reproduções  ·  %s", "%d plays  ·  %s" },
  { "%d reproduções registradas", "%d plays recorded" },
  { "%d títulos%s  ·  %s", "%d titles%s  ·  %s" },
  { "%d/10   %d curtidas", "%d/10   %d likes" },
  { "%dh %dmin Restantes", "%dh %dmin left" },
  { "%dh Restantes", "%dh left" },
  { "%dmin Restantes", "%dmin left" },
  { "%s  ·  %d de %d", "%s  ·  %d of %d" },
  { "%s assistidos", "%s watched" },
  { "%s por reprodução", "%s per play" },
  { "%s · %d reproduções", "%s · %d plays" },
  { "A seguir em %d s", "Up next in %d s" },
  { "ARQUIVO", "FILE" },
  { "Abra Fontes para escolher outra opção ou recarregar.", "Open Sources to pick another option or reload." },
  { "Abra um filme ou série e escolha Adicionar à lista para guardar.", "Open a movie or show and choose Add to library to keep it." },
  { "Abrindo fonte", "Opening source" },
  { "Addons", "Add-ons" },
  { "Adicionando à biblioteca...", "Adding to library..." },
  { "Adicionar à biblioteca", "Add to library" },
  { "Aguardando a autorização…", "Waiting for authorization…" },
  { "Ajustar altura", "Fit height" },
  { "Ajustar largura", "Fit width" },
  { "Ajustes", "Settings" },
  { "Alemão", "German" },
  { "Amarelo", "Yellow" },
  { "Amigo", "Friend" },
  { "Amigos assistindo", "Friends watching" },
  { "Animação", "Animation" },
  { "Animações", "Animations" },
  { "Ano: mais recentes", "Year: newest first" },
  { "Aponte a câmera do celular para o código:", "Point your phone camera at the code:" },
  { "Arredondamento", "Corner radius" },
  { "Arte indisponível", "Artwork unavailable" },
  { "Assistido", "Watched" },
  { "Atividade diária indisponível", "Daily activity unavailable" },
  { "Atividade privada ou não compartilhada", "Private or unshared activity" },
  { "Atividade recente", "Recent activity" },
  { "Atraso da expansão", "Expansion delay" },
  { "Atualizando biblioteca...", "Updating library..." },
  { "Atualizando · atividade anterior preservada", "Refreshing · previous activity kept" },
  { "Atualização indisponível · mostrando atividade anterior", "Refresh unavailable · showing previous activity" },
  { "Atualização indisponível · mostrando o último resumo recebido. %s", "Refresh unavailable · showing the last summary received. %s" },
  { "Automática", "Automatic" },
  { "Autorizado. Entrando…", "Authorized. Signing in…" },
  { "Avaliações", "Ratings" },
  { "Avaliações do Trakt", "Trakt ratings" },
  { "Avaliações gerais", "Overall ratings" },
  { "Aventura", "Adventure" },
  { "Azul", "Blue" },
  { "Ação", "Action" },
  { "Barra lateral", "Sidebar" },
  { "Barra lateral moderna", "Modern sidebar" },
  { "Biblioteca", "Library" },
  { "Biblioteca atualizada", "Library updated" },
  { "Biografia", "Biography" },
  { "Boas histórias conectam.", "Good stories connect people." },
  { "Botão de trailer", "Trailer button" },
  { "Branco", "White" },
  { "Brilho da borda", "Edge glow" },
  { "Busca", "Search" },
  { "Buscando fontes nos addons…", "Looking for sources in your addons…" },
  { "Buscar filmes e séries", "Search movies and TV shows" },
  { "CANCELADA", "CANCELED" },
  { "COLEÇÃO", "COLLECTION" },
  { "COLEÇÕES", "COLLECTIONS" },
  { "Carregando atividade…", "Loading activity…" },
  { "Carregando comentários…", "Loading comments…" },
  { "Carregando os perfis da sua conta…", "Loading your account profiles…" },
  { "Carregando títulos…", "Loading titles…" },
  { "Catálogo", "Catalog" },
  { "Catálogo organizado por serviço", "Catalog organized by service" },
  { "Catálogos do destaque", "Hero catalogs" },
  { "Chinês", "Chinese" },
  { "Cima/baixo: seções  ·  Voltar: menu", "Up/down: sections  ·  Back: menu" },
  { "Classificação", "Rating" },
  { "Cobertura da borda", "Edge coverage" },
  { "Coleção", "Collection" },
  { "Comentários", "Comments" },
  { "Completas", "Full" },
  { "Comédia", "Comedy" },
  { "Conecte o Trakt e assista a um filme ou episódio. Seu resumo usa somente o histórico disponível.", "Connect Trakt and watch a movie or episode. This summary only uses the history that is available." },
  { "Conta", "Account" },
  { "Conteúdo da Home", "Home content" },
  { "Continuar assistindo", "Continue Watching" },
  { "Coreano", "Korean" },
  { "Curta", "Short" },
  { "DIAS ATIVOS", "ACTIVE DAYS" },
  { "DIRETORES", "DIRECTORS" },
  { "Da conta", "From account" },
  { "Data de lançamento completa", "Full release date" },
  { "Desfocar não assistidos", "Blur unwatched" },
  { "Desfocar próximo episódio", "Blur next episode" },
  { "Desfoque da barra moderna", "Modern sidebar blur" },
  { "Desligado", "Off" },
  { "Desmarcado como assistido", "Marked as unwatched" },
  { "Desmarcando como assistido...", "Marking as unwatched..." },
  { "Desmarcar como assistido", "Mark as unwatched" },
  { "Detalhes do Filme", "Movie details" },
  { "Dia %d: %u reproduções", "Day %d: %u plays" },
  { "Digite ao menos 2 letras de um filme ou série.", "Type at least 2 letters of a movie or show." },
  { "Dinamarquês", "Danish" },
  { "Direita: resultados   •   Voltar: menu", "Right: results   •   Back: menu" },
  { "Diretor", "Director" },
  { "Direção", "Directed by" },
  { "Direção e Elenco", "Cast & Crew" },
  { "Documentário", "Documentary" },
  { "Dom", "Sun" },
  { "Duração", "Runtime" },
  { "EM EXIBIÇÃO", "AIRING" },
  { "ENTRE AMIGOS", "AMONG FRIENDS" },
  { "EPISÓDIO %d", "EPISODE %d" },
  { "EPISÓDIOS", "EPISODES" },
  { "Efeito de Profundidade", "Depth effect" },
  { "Efeito de profundidade", "Depth effect" },
  { "Elenco", "Cast" },
  { "Em Tipo, escolha Todos. Confira também os filtros em Ajustes.", "Under Type, choose All. Check the filters in Settings too." },
  { "Em alta", "Trending" },
  { "Entrar na sua conta", "Sign in to your account" },
  { "Entre amigos", "Among friends" },
  { "Episódio", "Episode" },
  { "Episódio %d", "Episode %d" },
  { "Episódios", "Episodes" },
  { "Espanhol", "Spanish" },
  { "Especiais", "Specials" },
  { "Esporte", "Sport" },
  { "Este pacote foi montado sem servidor.", "This package was built without a server." },
  { "Esticar", "Stretch" },
  { "Estilo do \"Continuar assistindo\"", "\"Continue Watching\" style" },
  { "Estilo streaming", "Streaming style" },
  { "Expandir pôster ao focar", "Expand poster on focus" },
  { "FILMOGRAFIA", "FILMOGRAPHY" },
  { "FINALIZADA", "ENDED" },
  { "Família", "Family" },
  { "Fantasia", "Fantasy" },
  { "Fechar", "Close" },
  { "Ficção científica", "Science Fiction" },
  { "Filme", "Movie" },
  { "Filmes", "Movies" },
  { "Filmes %.0f%%  ·  Episódios %.0f%%", "Movies %.0f%%  ·  Episodes %.0f%%" },
  { "Filmografia", "Filmography" },
  { "Filmografia em ordem cronológica", "Filmography in chronological order" },
  { "Finlandês", "Finnish" },
  { "Fixa", "Pinned" },
  { "Foco no Pôster", "Poster focus" },
  { "Fontes", "Sources" },
  { "Fora da biblioteca", "Not in library" },
  { "Francês", "French" },
  { "Fundo em tela cheia", "Full-screen backdrop" },
  { "Gradiente de foco clássico", "Classic focus gradient" },
  { "Grego", "Greek" },
  { "GÊNERO", "GENRE" },
  { "Hebraico", "Hebrew" },
  { "História", "History" },
  { "Histórico não consultado", "History not checked" },
  { "Holandês", "Dutch" },
  { "Húngaro", "Hungarian" },
  { "Idioma", "Language" },
  { "Idioma da legenda", "Subtitle language" },
  { "Idioma do áudio", "Audio language" },
  { "Indonésio", "Indonesian" },
  { "Inglês", "English" },
  { "Interface", "Interface" },
  { "Início", "Home" },
  { "Italiano", "Italian" },
  { "Japonês", "Japanese" },
  { "Lançamento", "Release" },
  { "Largo", "Wide" },
  { "Largura do item", "Item width" },
  { "Layout da Home", "Home layout" },
  { "Legendas", "Subtitles" },
  { "Ligado", "On" },
  { "Lista de prêmios configurada pelo usuário", "Awards list configured by the user" },
  { "Local do Descobrir", "Discover location" },
  { "Marcado como assistido", "Marked as watched" },
  { "Marcando como assistido...", "Marking as watched..." },
  { "Marcar como assistido", "Mark as watched" },
  { "Memória usada por imagens", "Memory used by images" },
  { "Miniatura do episódio", "Episode thumbnail" },
  { "Mistério", "Mystery" },
  { "Mostrar", "Show" },
  { "Mostrar \"Continuar assistindo\"", "Show \"Continue Watching\"" },
  { "Mostrar destaque", "Show hero" },
  { "Mostrar episódios não exibidos", "Show unaired episodes" },
  { "Mostrar na Busca", "Show in Search" },
  { "Música", "Music" },
  { "Na barra lateral", "In the sidebar" },
  { "Na biblioteca", "In library" },
  { "Navegação horizontal rápida", "Fast horizontal navigation" },
  { "Nenhum addon nesta conta.", "No add-ons in this account." },
  { "Nenhum comentário ainda.", "No comments yet." },
  { "Nenhum título nesta lista.", "No titles in this list." },
  { "Nenhum título neste filtro", "No titles under this filter" },
  { "Nenhum título recebido", "No titles received" },
  { "Nenhuma", "None" },
  { "Nenhuma faixa disponível nesta fonte.", "No track available in this source." },
  { "Nenhuma fonte direta disponível. Use Recarregar para tentar novamente.", "No direct source available. Use Reload to try again." },
  { "Nenhuma reprodução neste período", "No plays in this period" },
  { "No celular, abra:", "On your phone, open:" },
  { "Nome do addon no catálogo", "Addon name in catalog" },
  { "Norueguês", "Norwegian" },
  { "Notícias", "News" },
  { "Não assistido", "Not watched" },
  { "Não consegui falar com o servidor.", "Could not reach the server." },
  { "Não foi possível abrir a fonte", "Could not open the source" },
  { "Não foi possível atualizar o histórico.", "Could not refresh the history." },
  { "Não foi possível atualizar. Tente novamente.", "Could not update. Try again." },
  { "Não foi possível carregar os perfis. OK: tentar novamente", "Could not load the profiles. OK: try again" },
  { "Não foi possível carregar. OK para tentar novamente.", "Could not load. OK to try again." },
  { "Não foi possível confirmar este resumo agora.", "Could not confirm this summary right now." },
  { "O Trakt não liberou um histórico público para esta conta.", "Trakt did not expose a public history for this account." },
  { "O que vamos assistir?", "What are we watching?" },
  { "OK para explorar", "OK to explore" },
  { "OK · Tentar novamente", "OK · Try again" },
  { "OK · abrir título   ·   Voltar · fechar", "OK · open title   ·   Back · close" },
  { "OK: alterar", "OK: change" },
  { "OK: digitar   •   Voltar: menu", "OK: type   •   Back: menu" },
  { "OK: ligar ou desligar   ·   Voltar: Ajustes", "OK: enable or disable   ·   Back: Settings" },
  { "Ocultar", "Hide" },
  { "Ocultar não lançados", "Hide unreleased" },
  { "Opções do título", "Title options" },
  { "Ordem da lista", "List order" },
  { "Ordem original do ranking", "The ranking's original order" },
  { "Ordenar", "Sort" },
  { "Ordenação", "Sort order" },
  { "Original", "Original" },
  { "Os filmes e séries da sua coleção no Trakt ficam reunidos nesta aba.", "The movies and shows in your Trakt collection are gathered in this tab." },
  { "Os resultados dos addons aparecem aqui.", "Results from your addons show up here." },
  { "PIN de %s", "PIN for %s" },
  { "PIN incorreto", "Wrong PIN" },
  { "PRÊMIOS E CÂNONE", "AWARDS & CANON" },
  { "Padrão", "Default" },
  { "Painel ao pausar", "Pause panel" },
  { "País de Origem", "Country" },
  { "Perfil", "Profile" },
  { "Perfil e Stats", "Profile & Stats" },
  { "Perfil indisponível", "Profile unavailable" },
  { "Perfil privado ou histórico não compartilhado", "Private profile or unshared history" },
  { "Período não informado", "Period not given" },
  { "Pico: %d reproduções no dia %d", "Peak: %d plays on day %d" },
  { "Polonês", "Polish" },
  { "Popular - Filme", "Popular - Movies" },
  { "Popular - Série", "Popular - TV" },
  { "Português", "Portuguese" },
  { "Português (BR)", "Portuguese (BR)" },
  { "Preparando o código…", "Preparing the code…" },
  { "Preto", "Black" },
  { "Priorizar metadados externos", "Prefer external metadata" },
  { "Profundidade no \"Continuar\"", "Depth on \"Continue\"" },
  { "Profundidade no elenco", "Depth on cast" },
  { "Profundidade nos episódios", "Depth on episodes" },
  { "Profundidade nos pôsteres", "Depth on posters" },
  { "Profundidade nos trailers", "Depth on trailers" },
  { "Progresso salvo", "Progress saved" },
  { "Pronto.", "Done." },
  { "Proporção", "Aspect ratio" },
  { "Próximo", "Next" },
  { "Próximo do episódio mais alto", "Next up from furthest episode" },
  { "Próximo episódio", "Next episode" },
  { "Pular abertura", "Skip intro" },
  { "Pular resumo", "Skip recap" },
  { "Página de Detalhes", "Detail page" },
  { "Pôster", "Poster" },
  { "Pôsteres horizontais", "Landscape posters" },
  { "Qua", "Wed" },
  { "Qualidade máxima", "Maximum quality" },
  { "Quem está assistindo?", "Who's watching?" },
  { "Quem gerou o .ipk precisa informar a URL e a chave do projeto.", "Whoever built the .ipk must supply the project URL and key." },
  { "Qui", "Thu" },
  { "RANKING", "RANKING" },
  { "RENOVADA", "RENEWED" },
  { "REPRODUÇÕES", "PLAYS" },
  { "Ranking na ordem original", "Ranking in its original order" },
  { "Recarregar", "Reload" },
  { "Recolhida", "Collapsed" },
  { "Recomendações", "Recommendations" },
  { "Recortar", "Crop" },
  { "Reduzidas", "Reduced" },
  { "Reflexo", "Sheen" },
  { "Removendo da biblioteca...", "Removing from library..." },
  { "Remover da biblioteca", "Remove from library" },
  { "Reproduzindo", "Playing" },
  { "Reproduzindo agora", "Now playing" },
  { "Reproduzir", "Play" },
  { "Reproduzir / pausar", "Play / pause" },
  { "Reprodução", "Playback" },
  { "Reproduções", "Plays" },
  { "Retomada disponível   %d%%", "Resume available   %d%%" },
  { "Retomada disponível   %d%%   Episódio T%dE%d", "Resume available   %d%%   Episode S%dE%d" },
  { "Retomar", "Resume" },
  { "Retomar agora", "Resume now" },
  { "Ritmo de atividade", "Activity rhythm" },
  { "Romeno", "Romanian" },
  { "Roteirista", "Writer" },
  { "Russo", "Russian" },
  { "Rótulos nos pôsteres", "Poster labels" },
  { "SUA COMUNIDADE", "YOUR COMMUNITY" },
  { "Sair da conta", "Sign out" },
  { "Salvos", "Saved" },
  { "Se não aparecerem, confira a conexão ou tente outro nome.", "If nothing appears, check the connection or try another name." },
  { "Seg", "Mon" },
  { "Segure OK para opções", "Hold OK for options" },
  { "Seleção de cinema e séries", "A selection of film and TV" },
  { "Seleção do seu catálogo", "A selection from your catalog" },
  { "Sem arte", "No artwork" },
  { "Sem atividade pública por enquanto", "No public activity yet" },
  { "Sem conexão. Tente novamente.", "No connection. Try again." },
  { "Sem pôster", "No poster" },
  { "Separar futuros", "Split upcoming" },
  { "Serviço indisponível", "Service unavailable" },
  { "Setas: dias  ·  Voltar: menu", "Arrows: days  ·  Back: menu" },
  { "Setas: mover  ·  OK: escolher", "Arrows: move  ·  OK: choose" },
  { "Setas: títulos  ·  OK: detalhes", "Arrows: titles  ·  OK: details" },
  { "Sex", "Fri" },
  { "Sincronização", "Sync" },
  { "Sobre", "About" },
  { "Solte para abrir opções", "Release to open options" },
  { "Status", "Status" },
  { "Sua coleção aparece aqui", "Your collection shows up here" },
  { "Sua coleção no Trakt", "Your Trakt collection" },
  { "Sua conta", "Your account" },
  { "Sua lista para assistir", "Your watchlist" },
  { "Sua próxima sessão começa aqui", "Your next session starts here" },
  { "Sueco", "Swedish" },
  { "Sáb", "Sat" },
  { "Série", "TV Show" },
  { "Séries", "TV Shows" },
  { "TEMA", "THEME" },
  { "Tailandês", "Thai" },
  { "Tamanho dos itens", "Item size" },
  { "Tcheco", "Czech" },
  { "Temporada %d", "Season %d" },
  { "Tentar de novo", "Try again" },
  { "Ter", "Tue" },
  { "Terror", "Horror" },
  { "Tipo", "Type" },
  { "Tipo de conteúdo", "Content type" },
  { "Todas", "All" },
  { "Todos", "All" },
  { "Trailers", "Trailers" },
  { "Trakt desconectado", "Trakt disconnected" },
  { "Trakt · perfil público", "Trakt · public profile" },
  { "Trocar de usuário", "Switch user" },
  { "Turco", "Turkish" },
  { "TÍTULO SELECIONADO", "SELECTED TITLE" },
  { "Título: A a Z", "Title: A to Z" },
  { "Títulos do gênero no seu catálogo", "Titles of this genre in your catalog" },
  { "Ucraniano", "Ukrainian" },
  { "Uma curadoria por tema e atmosfera", "A curation by theme and mood" },
  { "Ver detalhes", "View details" },
  { "Ver tudo", "See all" },
  { "Verde", "Green" },
  { "Vermelho", "Red" },
  { "Versão", "Version" },
  { "Vietnamita", "Vietnamese" },
  { "Vincule o Trakt para carregar identidade, obras recentes e estatísticas.", "Link Trakt to load identity, recent activity and stats." },
  { "Você está assistindo", "You're watching" },
  { "Voltar retorna ao menu", "Back returns to the menu" },
  { "Zoom cinema", "Cinema zoom" },
  { "Zoom leve", "Slight zoom" },
  { "Zoom ultra", "Ultra zoom" },
  { "abril", "April" },
  { "agosto", "August" },
  { "apagar", "delete" },
  { "assistindo agora", "watching now" },
  { "assistiu", "watched" },
  { "atividade recente", "recent activity" },
  { "autorizacao negada no Trakt", "authorization denied by Trakt" },
  { "conferindo o manifesto…", "checking the manifest…" },
  { "dezembro", "December" },
  { "dias em sequência", "day streak" },
  { "dias em sequência no mês", "day streak this month" },
  { "e informe o código:", "and enter the code:" },
  { "espaço", "space" },
  { "fevereiro", "February" },
  { "fez check-in", "checked in" },
  { "janeiro", "January" },
  { "julho", "July" },
  { "junho", "June" },
  { "limpar", "clear" },
  { "lista", "list" },
  { "listas", "lists" },
  { "maio", "May" },
  { "março", "March" },
  { "novembro", "November" },
  { "não consegui desenhar o código", "could not draw the code" },
  { "não fornece nada que este app use", "provides nothing this app uses" },
  { "o Trakt respondeu sem token", "Trakt answered without a token" },
  { "outubro", "October" },
  { "pacote sem as chaves do Trakt", "package built without Trakt keys" },
  { "pacote sem endereco de login configurado", "package built without a login address" },
  { "perfil", "profile" },
  { "registrou um check-in", "checked in" },
  { "sem fio para falar com o Trakt", "no thread to talk to Trakt" },
  { "sem rede ao abrir sessao", "no network when opening the session" },
  { "setembro", "September" },
  { "título", "title" },
  { "títulos", "titles" },
  { "verificando…", "checking…" },
  { "Árabe", "Arabic" },
  { "Áudio", "Audio" },
  { "Última atividade: dia %d", "Last activity: day %d" },
  { "← Voltar", "← Back" },
  { "✓ Assistido%s%s", "✓ Watched%s%s" },
